// c:\Users\abduj\StudioProjects\per_rat\lib\data\models.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'anime_recommendation_response.dart';
export 'anime_response.dart';
export 'show_rating.dart';
export 'single_anime_response.dart';
export 'top_anime_response.dart';
export 'user_gender.dart';
