// c:\Users\abduj\StudioProjects\per_rat\lib\data\models.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:

export 'anime.dart';
export 'anime_model.dart';
export 'anime_response_freezed.dart';
export 'anime_response.dart';
export 'show_rating.dart';
export 'single_anime_response.dart';
export 'user_gender.dart';
